apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-demo-app1
  labels:
    app: sample-demo-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-demo-app1
  template:
    metadata:
      labels:
        app: sample-demo-app1
    spec:
      containers:
      - name: ang-app
        image: angproject:new4
        ports:
        - containerPort: 80